/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dhttmt11.tuan2;

import javax.swing.JButton;

/**
 *
 * @author DELL
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form DemoCalculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        hienThi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        so1 = new javax.swing.JButton();
        so2 = new javax.swing.JButton();
        so3 = new javax.swing.JButton();
        chia = new javax.swing.JButton();
        canB2 = new javax.swing.JButton();
        so4 = new javax.swing.JButton();
        so5 = new javax.swing.JButton();
        so6 = new javax.swing.JButton();
        nhan = new javax.swing.JButton();
        phanTram = new javax.swing.JButton();
        so7 = new javax.swing.JButton();
        so8 = new javax.swing.JButton();
        so9 = new javax.swing.JButton();
        tru = new javax.swing.JButton();
        nghichDao = new javax.swing.JButton();
        so0 = new javax.swing.JButton();
        congTru = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        cong = new javax.swing.JButton();
        bang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        mainPanel.setLayout(new java.awt.BorderLayout());

        hienThi.setBackground(new java.awt.Color(0, 204, 204));
        hienThi.setForeground(new java.awt.Color(204, 0, 0));
        hienThi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hienThi.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hienThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hienThi, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(4, 5));

        so1.setText("1");
        so1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPanel2.add(so1);

        so2.setText("2");
        so2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so2ActionPerformed(evt);
            }
        });
        jPanel2.add(so2);

        so3.setText("3");
        so3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so3ActionPerformed(evt);
            }
        });
        jPanel2.add(so3);

        chia.setText("/");
        chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiaActionPerformed(evt);
            }
        });
        jPanel2.add(chia);

        canB2.setText("sqrt");
        canB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canB2ActionPerformed(evt);
            }
        });
        jPanel2.add(canB2);

        so4.setText("4");
        so4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so4ActionPerformed(evt);
            }
        });
        jPanel2.add(so4);

        so5.setText("5");
        so5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so5ActionPerformed(evt);
            }
        });
        jPanel2.add(so5);

        so6.setText("6");
        so6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so6ActionPerformed(evt);
            }
        });
        jPanel2.add(so6);

        nhan.setText("*");
        nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanActionPerformed(evt);
            }
        });
        jPanel2.add(nhan);

        phanTram.setText("%");
        phanTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phanTramActionPerformed(evt);
            }
        });
        jPanel2.add(phanTram);

        so7.setText("7");
        so7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so7ActionPerformed(evt);
            }
        });
        jPanel2.add(so7);

        so8.setText("8");
        so8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so8ActionPerformed(evt);
            }
        });
        jPanel2.add(so8);

        so9.setText("9");
        so9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so9ActionPerformed(evt);
            }
        });
        jPanel2.add(so9);

        tru.setText("-");
        tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truActionPerformed(evt);
            }
        });
        jPanel2.add(tru);

        nghichDao.setText("1/x");
        nghichDao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nghichDaoActionPerformed(evt);
            }
        });
        jPanel2.add(nghichDao);

        so0.setText("0");
        so0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so0ActionPerformed(evt);
            }
        });
        jPanel2.add(so0);

        congTru.setText("+/-");
        congTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congTruActionPerformed(evt);
            }
        });
        jPanel2.add(congTru);

        xoa.setText("C");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });
        jPanel2.add(xoa);

        cong.setText("+");
        cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congActionPerformed(evt);
            }
        });
        jPanel2.add(cong);

        bang.setText("=");
        bang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangActionPerformed(evt);
            }
        });
        jPanel2.add(bang);

        mainPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private long a = 0;
    private float tam = 0;
    private boolean ktra = true;
    private String phepToan = "";

    private void so1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so1ActionPerformed
        // TODO add your handling code here:
        inPut(so1);
    }//GEN-LAST:event_so1ActionPerformed

    private void so2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so2ActionPerformed
        // TODO add your handling code here:
        inPut(so2);
    }//GEN-LAST:event_so2ActionPerformed

    private void so3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so3ActionPerformed
        // TODO add your handling code here:
        inPut(so3);
    }//GEN-LAST:event_so3ActionPerformed

    private void so4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so4ActionPerformed
        // TODO add your handling code here:
        inPut(so4);
    }//GEN-LAST:event_so4ActionPerformed

    private void so5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so5ActionPerformed
        // TODO add your handling code here:
        inPut(so5);
    }//GEN-LAST:event_so5ActionPerformed

    private void so6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so6ActionPerformed
        // TODO add your handling code here:
        inPut(so6);
    }//GEN-LAST:event_so6ActionPerformed

    private void so7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so7ActionPerformed
        // TODO add your handling code here:
        inPut(so7);
    }//GEN-LAST:event_so7ActionPerformed

    private void so8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so8ActionPerformed
        // TODO add your handling code here:
        inPut(so8);
    }//GEN-LAST:event_so8ActionPerformed

    private void so9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so9ActionPerformed
        // TODO add your handling code here:
        inPut(so9);
    }//GEN-LAST:event_so9ActionPerformed

    private void so0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so0ActionPerformed
        // TODO add your handling code here:
        inPut(so0);
    }//GEN-LAST:event_so0ActionPerformed

    private void chiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiaActionPerformed
        // TODO add your handling code here:
        tinhToan(chia);
    }//GEN-LAST:event_chiaActionPerformed

    private void nhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanActionPerformed
        // TODO add your handling code here:
        tinhToan(nhan);
    }//GEN-LAST:event_nhanActionPerformed

    private void truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truActionPerformed
        // TODO add your handling code here:
        tinhToan(tru);
    }//GEN-LAST:event_truActionPerformed

    private void congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congActionPerformed
        // TODO add your handling code here:
        tinhToan(cong);
    }//GEN-LAST:event_congActionPerformed

    private void canB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canB2ActionPerformed
        try {
            this.a = Long.parseLong(hienThi.getText());
            if (a > 0) {
                float b = (float) Math.sqrt(a);
                hienThi.setText(String.valueOf(b));
            } else {
                hienThi.setText("ERROR < 0 integer number");
            }
            myReset();
        } catch (NumberFormatException e) {
            tam = Float.parseFloat(hienThi.getText());
            if (tam > 0) {
                tam= (float) Math.sqrt(tam);
                hienThi.setText(String.valueOf(tam));
            } else {
                hienThi.setText("ERROR < 0 real number");
            }
            myReset();
        }
    }//GEN-LAST:event_canB2ActionPerformed

    private void phanTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phanTramActionPerformed
        try {
            this.a = Long.parseLong(hienThi.getText());
            float b = (float) a / 100;
            hienThi.setText(String.valueOf(b));
            myReset();
        } catch (NumberFormatException e) {
            tam = Float.parseFloat(hienThi.getText());
            tam = tam / 100;
            hienThi.setText(String.valueOf(tam));
            myReset();
        }
    }//GEN-LAST:event_phanTramActionPerformed

    private void nghichDaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nghichDaoActionPerformed
        try {
            this.a = Long.parseLong(hienThi.getText());
            a = 1 / a;
            hienThi.setText(String.valueOf(a));
            myReset();
        } catch (NumberFormatException e) {
            tam = Float.parseFloat(hienThi.getText());
            tam = 1 / tam;
            hienThi.setText(String.valueOf(tam));
            myReset();
        }
    }//GEN-LAST:event_nghichDaoActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        // TODO add your handling code here:
        myReset();
        hienThi.setText("0");
    }//GEN-LAST:event_xoaActionPerformed

    private void congTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congTruActionPerformed
        try { // so nguyen
            this.a = Long.parseLong(hienThi.getText());
            if (a < 0) {
                a = Math.abs(a);
            } else {
                a = (0 - a);
            }
            hienThi.setText(String.valueOf(a));
            myReset();
        } catch (NumberFormatException e) { // so thuc
            tam = Float.parseFloat(hienThi.getText());
            if (tam < 0) {
                tam = Math.abs(tam);
            } else {
                tam = (0 - tam);
            }
            hienThi.setText(String.valueOf(tam));
            myReset();
        }
    }//GEN-LAST:event_congTruActionPerformed

    private void bangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangActionPerformed
        // TODO add your handling code here:
        if (phepToan.length() > 0) {
            if (ktra) {
                long b = Long.parseLong(hienThi.getText());

                if (phepToan.equals("+")) {
                    long kq = a + b;
                    hienThi.setText(String.valueOf(kq));
                } else if (phepToan.equals("-")) {
                    long kq = a - b;
                    hienThi.setText(String.valueOf(kq));
                } else if (phepToan.equals("*")) {
                    long kq = a * b;
                    hienThi.setText(String.valueOf(kq));
                } else if (phepToan.equals("/")) {
                    float kq = (float) a / b;
                    hienThi.setText(String.valueOf(kq));
                }
            } else {
                long b = Long.parseLong(hienThi.getText());

                if (phepToan.equals("+")) {
                    float kq = (float) tam + b;
                    hienThi.setText(String.valueOf(kq));
                } else if (phepToan.equals("-")) {
                    float kq = (float) tam - b;
                    hienThi.setText(String.valueOf(kq));
                } else if (phepToan.equals("*")) {
                    float kq = (float) tam * b;
                    hienThi.setText(String.valueOf(kq));
                } else if (phepToan.equals("/")) {
                    float kq = (float) tam / b;
                    hienThi.setText(String.valueOf(kq));
                }
            }
        }
    }//GEN-LAST:event_bangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bang;
    private javax.swing.JButton canB2;
    private javax.swing.JButton chia;
    private javax.swing.JButton cong;
    private javax.swing.JButton congTru;
    private javax.swing.JLabel hienThi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton nghichDao;
    private javax.swing.JButton nhan;
    private javax.swing.JButton phanTram;
    private javax.swing.JButton so0;
    private javax.swing.JButton so1;
    private javax.swing.JButton so2;
    private javax.swing.JButton so3;
    private javax.swing.JButton so4;
    private javax.swing.JButton so5;
    private javax.swing.JButton so6;
    private javax.swing.JButton so7;
    private javax.swing.JButton so8;
    private javax.swing.JButton so9;
    private javax.swing.JButton tru;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables

    private void inPut(JButton so) {
        String gt = this.hienThi.getText();
        if (gt.length() < 12) {
            if (gt.equals("0")) {
                gt = "";
            }
            long soHienThi = Long.parseLong(gt + so.getText());
            this.hienThi.setText(String.valueOf(soHienThi));
        }
    }

    private void tinhToan(JButton pToan) {
        try {
            this.a = Long.parseLong(this.hienThi.getText());
            this.phepToan = pToan.getText();
            this.hienThi.setText("0");
            this.ktra = true;
        } catch (NumberFormatException e) {
            tam = Float.parseFloat(this.hienThi.getText());
            this.phepToan = pToan.getText();
            this.hienThi.setText("0");
            this.ktra = false;
        }
    }

    private void myReset() {
        a = 0;
        tam = 0;
        phepToan = "";
    }
}
